### ISSUE TITLE
experiment code

### ISSUE THREAD

**Issue by wjw136** [peterljq/Parsimonious-Concept-Engineering#1]
Thank you for your inspiring work and for releasing your dataset~
However, I couldn't find the code for the PaCE experiments. Could you please release the experimental code as well?

**Comment by peterljq** [comment]
Hi William,

Many thanks for your interest in our work! We have released the concept dataset in advance and we are actively structuring the code and scrutinizing LLM's responses in recent weeks. The complete pipeline will be released after ethical evaluation soon. If you have any questions during this period, please feel free to contact me through email or wechat, whichever you prefer. Thanks again!

Regards,

Jinqi
